---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-access-role
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-access-binding
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-access-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitoring
